
name: fuel_calculator
description: A Flutter application for calculating fuel costs.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  http: ^1.1.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

# Android permissions for Google Play Store
# These will be added to the AndroidManifest.xml file
android_permissions:
  - android.permission.INTERNET
  - android.permission.ACCESS_NETWORK_STATE

# iOS permissions
ios_permissions:
  - NSAppTransportSecurity
