// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guxaidzxhsvinjvmgpnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eGFpZHp4aHN2aW5qdm1ncG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTU2NzcsImV4cCI6MjA1ODI5MTY3N30.5Pxyrwk6cdD1WMwPRCcO2awFl4xOlbKFX-1l3o6lIMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);